apiVersion: apps/v1
kind: Deployment
metadata:
  name: soc-demo-service
  namespace: adaptive-soc
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: soc-demo-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: soc-demo-service
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: soc-demo-service
        image: soc-demo-service:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        envFrom:
        - configMapRef:
            name: soc-demo-service-config
        - secretRef:
            name: soc-demo-service-secrets
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
