apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: soc-demo-service-pdb
  namespace: adaptive-soc
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: soc-demo-service
